"""add_english_columns_plants_plantcare_users

Revision ID: 071add117552
Revises: f63901578ff6
Create Date: 2025-09-17 10:48:14.847128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071add117552'
down_revision: Union[str, None] = 'f63901578ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter les nouvelles colonnes anglaises
    op.add_column('plant_cares', sa.Column('location', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('name', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('species', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    
    # Migrer les données existantes
    op.execute("UPDATE users SET location = localisation WHERE localisation IS NOT NULL")
    op.execute("UPDATE plants SET name = nom WHERE nom IS NOT NULL")
    op.execute("UPDATE plants SET species = espece WHERE espece IS NOT NULL")
    op.execute("UPDATE plant_cares SET location = localisation WHERE localisation IS NOT NULL")
    
    # Rendre les nouvelles colonnes non-nullable après migration pour les champs obligatoires
    op.alter_column('plants', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restaurer les données vers les anciennes colonnes si elles existent encore
    op.execute("UPDATE users SET localisation = location WHERE location IS NOT NULL")
    op.execute("UPDATE plants SET nom = name WHERE name IS NOT NULL")
    op.execute("UPDATE plants SET espece = species WHERE species IS NOT NULL")
    op.execute("UPDATE plant_cares SET localisation = location WHERE location IS NOT NULL")
    
    # Supprimer les colonnes anglaises
    op.drop_column('users', 'location')
    op.drop_column('plants', 'species')
    op.drop_column('plants', 'name')
    op.drop_column('plant_cares', 'location')
    # ### end Alembic commands ###
