"""add_photo_base64_fields

Revision ID: 08b55fac9c06
Revises: b6ed35cdca54
Create Date: 2025-09-13 09:51:48.229237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b55fac9c06'
down_revision: Union[str, None] = 'b6ed35cdca54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'photo_base64')
    # ### end Alembic commands ###
