"""neon_schema_update

Revision ID: 8494fbbf9724
Revises: 7a013e7dcad2
Create Date: 2025-09-12 15:18:14.300018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8494fbbf9724'
down_revision: Union[str, None] = '7a013e7dcad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
