"""add_base64_image_storage

Revision ID: b6ed35cdca54
Revises: 8494fbbf9724
Create Date: 2025-09-13 10:44:18.727179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ed35cdca54'
down_revision: Union[str, None] = '8494fbbf9724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_reports', sa.Column('photo_base64', sa.Text(), nullable=True))
    op.add_column('plants', sa.Column('photo_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'photo_base64')
    op.drop_column('care_reports', 'photo_base64')
    # ### end Alembic commands ###
