"""add_english_columns_all_tables

Revision ID: f63901578ff6
Revises: f997224f0474
Create Date: 2025-09-17 10:47:14.531177

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f63901578ff6'
down_revision: Union[str, None] = 'f997224f0474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
