"""Remove description field from plants table

Revision ID: f744e4ac549b
Revises: 231ef0d05ec9
Create Date: 2025-08-31 05:42:27.396053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f744e4ac549b"
down_revision: Union[str, None] = "231ef0d05ec9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plants", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plants",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
