version: '3.8'

services:
  api:
    container_name: arosa-je-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./api/assets/database:/app/assets/database
      - ./api/assets/img:/app/assets/img
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.api
    environment:
      - DATABASE_URL=sqlite:///assets/database/arosaje.db
      - PYTHONUNBUFFERED=1
    networks:
      - arosa-je-network
    restart: "no"

  web:
    container_name: arosa-je-web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./env/.env.web
    environment:
      - NODE_ENV=development
    networks:
      - arosa-je-network
    depends_on:
      - api
    restart: "no"
    command: npm run dev

  mobile:
    container_name: arosa-je-mobile
    build:
      context: ./mobile
      dockerfile: Dockerfile
    volumes:
      - ./mobile:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    networks:
      - arosa-je-network
    restart: "no"

networks:
  arosa-je-network:
    name: arosa-je-network
