server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs de l'API FastAPI
  - job_name: api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          __path__: /var/log/api/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            user_id: user_id
            endpoint: endpoint
            method: method
            status_code: status_code
            response_time: response_time
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          endpoint:
          method:
          status_code:

  # Logs de l'application Web
  - job_name: web-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: web
          __path__: /var/log/web/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            page: page
            user_agent: user_agent
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          page:

  # Logs des containers Docker
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Logs système (si disponibles)
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog 