global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter pour les métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor désactivé temporairement (problème WSL)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # API FastAPI avec métriques Prometheus
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Application Web Next.js (si métriques exposées)
  - job_name: 'web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # InfluxDB métriques
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'

  # PostgreSQL principal (avec postgres_exporter si configuré)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    # Nécessiterait postgres_exporter

  # Redis métriques (avec redis_exporter si configuré)  
  - job_name: 'redis'
    static_configs:
      - targets: ['api-redis:6379']
    # Nécessiterait redis_exporter 