apiVersion: 1

datasources:
  # Prometheus pour les métriques techniques
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # Loki pour les logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  # InfluxDB pour les métriques business
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: arosaje-token-12345678
    jsonData:
      version: Flux
      organization: arosaje
      defaultBucket: metrics
      tlsSkipVerify: true
    editable: true

  # PostgreSQL de monitoring pour les logs structurés
  - name: Monitoring PostgreSQL
    type: postgres
    access: proxy
    url: monitoring-postgres:5432
    database: monitoring_db
    user: monitoring
    secureJsonData:
      password: monitoring_password_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true 