name: API Tests

on:
  pull_request:
    paths:
      - 'api/**'
  push:
    branches: [ main, develop ]
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Service Redis pour les tests
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Redis CLI
        run: |
          # Installer redis-cli
          sudo apt-get update
          sudo apt-get install -y redis-tools
          redis-cli --version
          
      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          
      - name: Create required directories
        working-directory: ./api
        run: |
          mkdir -p assets/persisted_img
          mkdir -p assets/temp_img
          mkdir -p assets/img
          mkdir -p assets/database
          mkdir -p logs
          # S'assurer que les permissions sont correctes
          chmod -R 777 assets
          chmod -R 777 logs
      
      - name: Préparer la base de données SQLite
        working-directory: ./api
        run: |
          # Créer un fichier vide pour la base de données SQLite
          touch assets/database/test.db
          chmod 666 assets/database/test.db
          
          # Vérifier que le fichier est accessible
          ls -la assets/database/
      
      - name: Vérifier la connexion Redis
        run: |
          # Vérifier que Redis est accessible
          redis-cli ping
      
      - name: Create test environment file
        working-directory: ./api
        run: |
          # Créer le fichier d'environnement pour les tests
          cat > .env.test << EOL
          DATABASE_URL=sqlite:///assets/database/test.db
          REDIS_URL=redis://localhost:6379
          REDIS_PASSWORD=
          ENVIRONMENT=test
          JWT_SECRET=test_secret_key_for_github_actions
          MAIL_USERNAME=test@example.com
          MAIL_PASSWORD=test_password
          MAIL_FROM=test@example.com
          MAIL_PORT=587
          MAIL_SERVER=smtp.example.com
          MAIL_FROM_NAME=Test API
          MAIL_STARTTLS=false
          MAIL_SSL_TLS=false
          USE_CREDENTIALS=false
          DISABLE_EMAIL=true
          # Variables pour les tests qui utilisent un compte admin
          ADMIN_EMAIL=admin@example.com
          ADMIN_PASSWORD=admin123secure
          LOG_LEVEL=DEBUG
          LOG_FILE=logs/api.log
          EOL
          
          cat .env.test
          
          # Tester la connexion SQLite
          cat > test_sqlite.py << EOL
          from sqlalchemy import create_engine, text
          import os
          
          db_url = "sqlite:///assets/database/test.db"
          print(f"Test de connexion à {db_url}")
          
          engine = create_engine(db_url)
          with engine.connect() as conn:
              conn.execute(text("CREATE TABLE IF NOT EXISTS test (id INTEGER PRIMARY KEY)"))
              conn.execute(text("INSERT INTO test VALUES (1)"))
              result = conn.execute(text("SELECT * FROM test")).fetchall()
              print(f"Résultat du test: {result}")
          EOL
          
          python test_sqlite.py
          
          # Tester la connexion Redis
          cat > test_redis.py << EOL
          import redis
          
          r = redis.Redis(host='localhost', port=6379, db=0)
          print("Test de connexion à Redis...")
          
          # Tester set/get
          r.set('test_key', 'test_value')
          result = r.get('test_key')
          print(f"Résultat du test Redis: {result}")
          EOL
          
          python test_redis.py

      - name: Créer un compte admin pour les tests
        working-directory: ./api
        run: |
          # Script pour créer un compte admin
          cat > create_admin.py << EOL
          import os
          import sys
          from sqlalchemy import create_engine, text
          
          # Configurer la base de données
          db_url = "sqlite:///assets/database/test.db"
          engine = create_engine(db_url)
          
          # Créer la table utilisateurs si elle n'existe pas
          with engine.connect() as conn:
              conn.execute(text("""
                  CREATE TABLE IF NOT EXISTS users (
                      id INTEGER PRIMARY KEY AUTOINCREMENT,
                      nom TEXT NOT NULL,
                      prenom TEXT NOT NULL,
                      email TEXT UNIQUE NOT NULL,
                      password_hash TEXT NOT NULL,
                      telephone TEXT,
                      localisation TEXT,
                      verified INTEGER DEFAULT 0,
                      role TEXT DEFAULT 'user'
                  )
              """))
              
              # Vérifier si l'admin existe déjà
              result = conn.execute(text("SELECT id FROM users WHERE email = 'admin@example.com'")).fetchone()
              
              if not result:
                  # Insérer l'admin
                  conn.execute(text("""
                      INSERT INTO users (nom, prenom, email, password_hash, telephone, localisation, verified, role)
                      VALUES ('Admin', 'User', 'admin@example.com', 
                             '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', 
                             '0123456789', 'Admin Location', 1, 'admin')
                  """))
                  print("Compte admin créé avec succès")
              else:
                  print("Le compte admin existe déjà")
          EOL
          
          python create_admin.py

      - name: Start API server
        working-directory: ./api
        run: |
          # Définir explicitement les variables d'environnement
          export DATABASE_URL="sqlite:///assets/database/test.db"
          export REDIS_URL="redis://localhost:6379"
          export ADMIN_EMAIL="admin@example.com"
          export ADMIN_PASSWORD="admin123secure"
          export LOG_LEVEL=DEBUG
          export LOG_FILE=logs/api.log
          
          # Démarrer l'API en mode test avec la base SQLite
          # Rediriger stdout et stderr vers un fichier de log spécifique
          nohup python -m uvicorn main:app --host 0.0.0.0 --port 8000 --env-file .env.test > logs/uvicorn.log 2>&1 &
          echo $! > api_pid.txt
          
          # Attente active pour que le serveur soit prêt
          echo "Attente du démarrage de l'API..."
          max_retries=30
          retries=0
          until $(curl --output /dev/null --silent --fail http://localhost:8000/health); do
            if [ $retries -eq $max_retries ]; then
              echo "L'API n'a pas démarré après $max_retries tentatives"
              cat logs/uvicorn.log
              if [ -f logs/api.log ]; then
                cat logs/api.log
              fi
              exit 1
            fi
            printf '.'
            retries=$((retries+1))
            sleep 2
          done
          echo "API démarrée avec succès!"
          curl -v http://localhost:8000/health
      
      - name: Run tests
        working-directory: ./api
        run: |
          # Vérifier à nouveau la disponibilité de l'API avant de lancer les tests
          curl -v http://localhost:8000/health
          
          # Exécuter les tests avec SQLite et Redis
          export DATABASE_URL="sqlite:///assets/database/test.db"
          export REDIS_URL="redis://localhost:6379"
          export ADMIN_EMAIL="admin@example.com"
          export ADMIN_PASSWORD="admin123secure"
          
          # Exécuter d'abord le test auth qui crée les utilisateurs
          python -m pytest tests/workflows/test_auth_workflow.tavern.yaml -v
          
          # Puis exécuter les autres tests
          python -m pytest tests/workflows/ -v
      
      - name: API logs en cas d'échec
        if: ${{ failure() }}
        working-directory: ./api
        run: |
          echo "=== Logs de l'API (Uvicorn) ==="
          if [ -f logs/uvicorn.log ]; then
            cat logs/uvicorn.log
          else
            echo "Fichier logs/uvicorn.log introuvable"
          fi
          
          echo "=== Logs de l'API (Application) ==="
          if [ -f logs/api.log ]; then
            cat logs/api.log
          else
            echo "Fichier logs/api.log introuvable"
            ls -la logs/
          fi
          
          echo "=== Contenu du répertoire logs ==="
          ls -la logs/
          
          echo "=== Contenu du répertoire de la base de données ==="
          ls -la assets/database/
          
          echo "=== Configuration de la base de données ==="
          grep -r "DATABASE_URL\|engine\|create_engine\|sqlite" --include="*.py" .
          
          echo "=== Test Redis ==="
          redis-cli ping
          redis-cli keys '*'
          
      - name: Arrêt de l'API
        if: ${{ always() }}
        working-directory: ./api
        run: |
          if [ -f api_pid.txt ]; then
            kill $(cat api_pid.txt) || true
          fi 