name: API Tests

on:
  pull_request:
    paths:
      - 'api/**'
  push:
    branches: [ main, develop ]
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Service PostgreSQL pour les tests
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: arosaje_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Service Redis pour les tests
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          
      - name: Create required directories
        working-directory: ./api
        run: |
          mkdir -p assets/persisted_img
          mkdir -p assets/temp_img
          mkdir -p assets/img
          mkdir -p logs
      
      - name: Start API server
        working-directory: ./api
        run: |
          # Démarrer l'API en arrière-plan
          python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
          # Attendre que le serveur soit prêt
          sleep 10
        env:
          # Variables d'environnement pour les tests
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/arosaje_test
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
          JWT_SECRET: test_secret_key_for_github_actions
      
      - name: Run tests
        working-directory: ./api
        run: |
          pytest tests/workflows/ -v
        env:
          # Variables d'environnement pour les tests
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/arosaje_test
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
          JWT_SECRET: test_secret_key_for_github_actions 